name: super_app_telemedicine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.5
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_polyline_points: ^2.0.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  photo_view: ^0.15.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/category_doctor/
    - assets/category_obat/
    - assets/category_spesialis/
    - assets/logo_bank/
